---
title: "biweekly5"
author: "Julia Shoobe"
date: "10/25/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Install and Load Packages
```{r}
#install.packages("tidyverse") #run once, then comment out
#install.packages("data.table") #run once, then comment out
#install.packages("readr") #run once, then comment out
#install.packages("dplyr") #run once, then comment out
library(tidyverse)
library(data.table)
library(readr)
library(dplyr)
```
#Import Datasets
```{r}
fludata <- read.csv("~/Desktop/fludata.csv")
```
#Data Subsets: By Age
```{r}
zero_to_four <- filter(fludata, AGE == "0-4 yrs")
five_to_seventeen <- filter(fludata, AGE == "5-17 yrs")
eighteen_to_fourtynine <- filter(fludata, AGE == "18-49 yrs")
fifty_to_sixtyfour <- filter(fludata, AGE == "50-64 yrs")
sixtyfive_plus <- filter(fludata, AGE == "65+ yrs")
```
#Graph Showing Symptoms With Year and Age
```{r}
#One graph with age separated by color
illness <- ggplot(data=fludata) +
  geom_point(aes(x=YEAR, y=SYMPTOMATIC.ILLNESSES, color = AGE)) +
  theme(axis.text = element_text(size = 5)) +
  labs(title="Symptomatic Illnesses Separated by Age", x="Year Studied", y="Symptomatic Illnesses")
illness

#Different graphs for each age group
illness1 <- ggplot(data=fludata) +
  geom_point(aes(x=YEAR, y=SYMPTOMATIC.ILLNESSES)) +
  facet_wrap(~AGE) +
  theme(axis.text = element_text(size = 5)) +
  labs(title="Symptomatic Illnesses Separated by Age", x="Year Studied", y="Symptomatic Illnesses")
illness1
```
#Graph Showing Medical Visits with Year and Age
```{r}
#One graph with age separated by color
doctor <- ggplot(data=fludata) +
  geom_point(aes(x=YEAR, y=MEDICAL.VISITS, color = AGE)) +
  theme(axis.text = element_text(size = 5)) +
  labs(title="Medical Visits Separated by Age", x="Year Studied", y="Medical Visits")
doctor

#Different graphs for each age group
visits1 <- ggplot(data=fludata) +
  geom_point(aes(x=YEAR, y=MEDICAL.VISITS)) +
  facet_wrap(~AGE) +
  theme(axis.text = element_text(size = 5)) +
  labs(title="Medical Visits Separated by Age", x="Year Studied", y="Medical Visits")
visits1
```
#Graph Showing Hospitalizations with Year and Age
```{r}
#One graph with age separated by color
hospital <- ggplot(data=fludata) +
  geom_point(aes(x=YEAR, y=HOSPITALIZATIONS, color = AGE)) +
  theme(axis.text = element_text(size = 5)) +
  labs(title="Hospitalizations Separated by Age", x="Year Studied", y="Hospitalizations")
hospital

#Different graphs for each age group
hospital1 <- ggplot(data=fludata) +
  geom_point(aes(x=YEAR, y=HOSPITALIZATIONS)) +
  facet_wrap(~AGE) +
  theme(axis.text = element_text(size = 5)) +
  labs(title="Hospitalizatons Separated by Age", x="Year Studied", y="Hospitalizations")
hospital1
```
#Graph Showing Deaths with Year and Age
```{r}
#One graph with age separated by color
death <- ggplot(data=fludata) +
  geom_point(aes(x=YEAR, y=DEATHS, color = AGE)) +
  theme(axis.text = element_text(size = 5)) +
  labs(title="Deaths Separated by Age", x="Year Studied", y="Deaths")
death

#Different graphs for each age group
death1 <- ggplot(data=fludata) +
  geom_point(aes(x=YEAR, y=DEATHS)) +
  facet_wrap(~AGE) +
  theme(axis.text = element_text(size = 5)) +
  labs(title=" Deaths Separated by Age", x="Year Studied", y="Deaths")
death1
```

